name: CI

on:
push:
  branches-ignore:
    - "production"
    - "docs"
  paths-ignore:
    - ".github/**"
    - "!.github/workflows/ci.yml"
    - ".gitignore"
pull_request:
  paths:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for post's lastmod

      # this automatically gets bug fixes and new Ruby versions
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches the result

      - name: Test Site
        run: bash tools/test
